name: "auto assign"

on:
  pull_request:
    types: [opened, edited]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Assign Action
        uses: ./
        with:
          config: ".github/auto-assigner.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
